---
- name: Validate containerd configuration
  ansible.builtin.command: containerd --config /etc/containerd/config.toml config dump
  changed_when: false
  listen: Restart containerd

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted
  listen: Restart containerd

- name: Wait for the containerd socket
  ansible.builtin.wait_for:
    path: /run/containerd/containerd.sock
    state: present
    timeout: 30
  listen: Restart containerd
