apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:gBnnm6GFfRQzFNY7Cy4weTthskOZzldJ6WWLoS1Pt+IroHE9HTsyMlXs6KehMJJHvz+8trM=,iv:lOGkLocT0ba8OSIbkD9I/G7U1ZQF0VC/6rvpRUGLMUg=,tag:3SB5R9TUYuWanHPFLMS8fQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdXdldGNMbWg3d2RXWjFE
            WjdZa0Z3bmdXVC9EZXBad2JvWXEvbDh1Q0FVClRPSE9FL2JBb1psQUFTL2pDbjk4
            dzcrTzZ4TUIzeFd4a2dYUDRmeEhqYWsKLS0tIHdvak5Dd2dnWHNKYkNmd3VYR1Jm
            VzFjWGNXcnRxT2NVVHlscWp3QW1MczgKfQ9qkUZvfUSuiaK2W7sepzvg5AoQv2gS
            kIAN+BFIMRBYlG8lX3ut8TzNFRM+OItWi0bqVtXy4T5SUXWopk0vLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdnhpr5c2nt2j7jncce24vaa3r55kjzej4x9x74h2f08janvaps2xfgr4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T22:44:58Z"
    mac: ENC[AES256_GCM,data:Rk8Iaw65lEFiUWB9YcTrZVeCsNEa4rE16EX/mZY0YvAxdZZveszavMbpOHB5FIf1J+GBC0zxMsGcFV5KEaDCv272TcIBewgUmmPtNHvbvpA9qr130dPJvzJBc0pVw76AboAGQac7k38UbB9EhXFEnLE9qc9Jvy96qUjlTq+8snk=,iv:/xe3NnEIKRBvcLAmBZCRmyXEP42TGRvsKM5oBZpkcQA=,tag:WGiNkr3PvtMHshL8mshNKQ==,type:str]
    version: 3.13.3
