apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ra1oLlvVLRmRUrA=,iv:vtJy2DLCLcZQ3+LjagoIUdXciD3K4aNFwzUzrdE6Myc=,tag:/sGpA/foEpz7m8HSUdot8A==,type:str]
    password: ENC[AES256_GCM,data:r7WFoA7+VXg1RcFfS3JOAwGQdnQL/UI5eIn6xB7lkahd8UFUMZuFlML1R0fh6Hz/,iv:8gN9sI5lu6j33kgrNKpuxhmcVYl7sQXF5sEd258MpII=,tag:W6sU/iOlqjSq3T5y5EAMcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS0JEemtOSVFmZG1zTXBX
            ZEZueTdtcElUcDBYcFM0dU5CZ0JTbXh3Y1I0ClB0K0FneGFrN2IxZkVkS1J1NEhj
            ZDZveDVNYnVHZUlxd0F3Nm1ZaWtFdVkKLS0tIE9vSDl5QWpJc2Noa25aWUZnc2hi
            TERrYXhheHFIWEJQWUdZOVhmbXBRdUUKVi3vcPpqLVgsyXudY5MMGi2MLJBYgAnR
            lPu7+1pCS46qhSvyUOSCmlgUP8GX1/RAiLI7wIuPi/GtG0MpqV7rTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdnhpr5c2nt2j7jncce24vaa3r55kjzej4x9x74h2f08janvaps2xfgr4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T23:10:04Z"
    mac: ENC[AES256_GCM,data:3tAxJmpRJqbNrMw2yQrgIy49CybE0oMRRn8osawoo+fRtc2tJjUO9SUbhWL6yWLu4q96/zwWx/89s36fdouhXKVc88XEgRt0aneshi9EsbrDC8B+JMW/13UcSF1s4nwA+HXv7a/oiU8mY0v+BStmdfHB5GBsHiBfO2GtgUzd8b4=,iv:a2dSAyTk02M8Z/xeS1Y4MrL7CLa6tlgDPJD9wfMZ1WI=,tag:BLIU/WpnvmgRXaEu7E4veQ==,type:str]
    version: 3.13.3
