apiVersion: v1
kind: Secret
metadata:
    name: gitea-database
    namespace: gitea
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:bIpqyJr9s2D4OnbFN0MPqkUsDiAWccYneYEM5JWgLuMg5f0ZmhzOBsEFxKlsVV4p,iv:0kY8gzOWx8CqJPI3qJL3w9WeDnSxXupN9jRpDW25k2w=,tag:82k2ZF7pJ5VD5ZP4HqsDSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZndVaHoweWR1ZHQrQnFQ
            d2FNRGNhUHRNRnhwNnhONU5UcGxmR3FaTkVzCnNhWWFqNWZIRXoyaDRXSnJBUWI4
            di9kNXQ3Q21neDFrL2FsSmo2ajlITU0KLS0tICtHNHBINjRCekxkL3BsUGdTQnc4
            QnQwc0Z1UGduWFdxQkhKZkcvYXdSNWcKe2icmNc6OLwmge3jOoiXzEFMcvrNiQnM
            HZUh1lWqpeWTCZEVuJn2t6LMr4MAKIh5yxY4rppXNG1TytOIWlDOKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdnhpr5c2nt2j7jncce24vaa3r55kjzej4x9x74h2f08janvaps2xfgr4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T23:10:04Z"
    mac: ENC[AES256_GCM,data:pfPXbORJ/dFRvnqJjPHjyoPW/zK+AvyXE7gB9AsMURjIgIqpnQtB96oqTXgLBuqeE/Cy75crZlj+YY87qtITMdl4/uJC76fmr2Q2ZPU5mrQpWpz7wdLoHJ+wCJyb2VVbSR1m7gb2GIOhzCmHSPAiXkkkr1n+HZ1BJrR6bdXzpyM=,iv:EfytpJdRyqjKD5IYIkAFF+8GbZI4C5Bq4J5z5NnHofg=,tag:Y1fsnY3GXJF5hYuYk/jNkw==,type:str]
    version: 3.13.3
