apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: postgresql
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:79qun21FyUkdtVaMeejAmDsbE5e/4JjpvtIuNLdkTLM3odpD39gPd5Hs+CWh3NCn,iv:+1nED/mHQGATVYMk4YNVShr7H1uhAbVOjGQ+Fsuq7O0=,tag:QTX0kOhJ/Hg1auCc2HB7zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cHI3eFUxUkVadTl3dm0w
            NEhyV2g1a1lvUFE4TGVUNWRZZ3RQMTFtNGg0CjF0SjNsa1Q4SFFnQ1FXOFNNdUpp
            YVZyZGxNYzhuYUpIK2k1ZmtGZWpsTXcKLS0tIGZSY0x3SDFNdnZsM1NyQVJnSXI1
            ZGxQL0JHcis5VXZvMitXZURtM2xWSGsK8dWeDYj6sYfz0JyO3IDjuZUSZQyPQu18
            MW3UBmJLIRXCMknlO20miFbVDFJAp7rsSvZbE383u3WjM/AIIKX9ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cxdnhpr5c2nt2j7jncce24vaa3r55kjzej4x9x74h2f08janvaps2xfgr4
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T23:10:04Z"
    mac: ENC[AES256_GCM,data:4yRZDo2YCCgTrzATebie070hyDKZKT3S3FMb3dvVsYceBgZL/hjBSxwWqe7WJGVBEmCYIiDek7h1Wtdwq+d2yOcQGeQEHcyV7cx/Plzp8Eb9L/BJSeM3+LUjBBiaJZ0265lhWcCMiPGdcgDUaE37dKNKZMK0izwSBRXDfVLgXsU=,iv:jxNDT8TbIndUCKLIZ3KWZqr7ucIayBiMpQTbCoLqs3c=,tag:5sR0sBb1sB51dd2LnRIVfQ==,type:str]
    version: 3.13.3
